### ISSUE TITLE
version 1.5.1 does not include QNX patch

### ISSUE THREAD

**Issue by asobhy-qnx** [ament/google_benchmark_vendor#7]
need to use master branch to include QNX patch in google benchmark commit 1302d2ce094a9753b0f81a81ea74c0fa71fae582

**Comment by asobhy-qnx** [comment]
@dirk-thomas please let me know how you would like to move forward with this issue

**Comment by dirk-thomas** [comment]
There isn't a released version containing the patch yet. But this package could pull the archive from e.g. the commit hash of the current head. Please create a pull request updating the URL and MD5 and including a comment why it is necessary.
